### ISSUE TITLE
min and max threads setting

### ISSUE THREAD

**Issue by jonathangreen** [cantaloupe-project/cantaloupe#228]
Hello. 

I'm having an issue where Cantaloupe is able to clobber the old backend server that actually serves up my images. That is an issue in itself, until I can make that server scale a bit better I'm looking for a way to somewhat rate limit cantaloupe, so it doesn't flood the backend server with too many requests. 

I was thinking about trying to limit the number of concurrent requests cantaloupe can handle to rate limit things. 

That lead me to this commit: https://github.com/medusa-project/cantaloupe/commit/c1e61281fd7c25f0a76b57ce04b288b65b7f80af

I was wondering if `http.min_threads` and `http.max_threads` were causing any issues? Or if I might be able to resurrect this commit and test it out? 

Thanks.

**Comment by adolski** [comment]
I think those config keys relate to some experimentation I was doing that I later decided I shouldn't have committed. Maybe they would help with this situation (but it would be better to scale the backend server, like you said).

For experimenting, this is the part that configures Jetty:

https://github.com/medusa-project/cantaloupe/blob/f98fec1a574652d3eecbab37ff0c60226ac83006/src/main/java/edu/illinois/library/cantaloupe/ApplicationServer.java#L140-L143

I'm open to resurrecting this if it would be useful to anyone.

**Comment by MorrisonCole** [comment]
@adolski hey there, sorry to resurrect an old thread! 🧓 

We ran into a issue recently when running some load tests with Cantaloupe serving images. We have a load balancer in front of a few parallel Cantaloupe instances, but since Cantaloupe happily accepts a bunch of requests at once, it's hard to scale horizontally.

Problem is that performance degrades pretty rapidly at high concurrency, so we'd like to limit it so that requests can be serviced by other instances. Right now we've done the same thing as the OP, which is to make a custom build with that commit reverted. Would be nice to have some configuration handles so that we can avoid diverging from main 🙏

**Comment by yuricaprini** [comment]
@MorrisonCole Hi Morrison, sorry to bother you on an old thread, but I’ve run into the same issue you described, and I’m not sure I fully understand your solution. I thought maybe you could help clarify it (for me and the community).

I have a load balancer (Nginx) distributing requests across n Cantaloupe instances in a round-robin fashion. You mentioned that, to avoid performance degradation under heavy load (high concurrency), one option is to limit the maximum number of threads so that other instances can take over. Otherwise, Cantaloupe “happily accepts a bunch of requests at once,” making it “hard to scale horizontally.”

What I don’t understand is why this happens. Round-robin should guarantee that requests are evenly distributed regardless of Cantaloupe’s behaviour—shouldn’t it? Am I missing something? Maybe your load balancer was using a different policy?

Thanks in advance for any insight you can share!

**Comment by MorrisonCole** [comment]
It's been a long while since I've worked on the project I mentioned there (and no longer have access), but I remember we were running Cantaloupe on EC2 and using an AWS ALB without much additional configuration. 

The part you're missing I think is the horizontal scaling - since Cantaloupe just spawned a bunch of worker theads and handled requests (albeit with huge application perf. degradation), unless an instance literally died, the LB would continue to assign traffic without starting new instances to handle the increase. 

I can't remember what metrics we had set up autoscaling to watch, but I remember with this change reverted it behaved much better.

Think we probably limited it to <16 threads with the EC2 instance types we had at the time.
