### ISSUE TITLE
Cantaloupe with IIIF Search API?

### ISSUE THREAD

**Issue by m-art-in** [cantaloupe-project/cantaloupe#285]
Any change, that Cantaloupe will support the Search API soon? I would appreciate that very much.

**Comment by adolski** [comment]
Thanks for the feedback, @m-art-in . The IIIF Image and Search APIs are in completely different domains, and it's safe to say that Cantaloupe will remain only an image server. But the IIIF APIs are designed to mesh together so that different implementations of each can work together in a standard way. So, Cantaloupe can be used alongside implementations of the other IIIF APIs, without implementing them itself.

**Comment by m-art-in** [comment]
Thanks for the you answer and explanation. I hoped to run only one server for images, presentation and full text. So I have to keep Cantaloupe running and for my full texts I use https://github.com/glenrobson/SimpleAnnotationServer.

Or do you have a recommendation for a one for all solution?
