### ISSUE TITLE
Question: is a pass through processor possible? A/V

### ISSUE THREAD

**Issue by DiegoPino** [cantaloupe-project/cantaloupe#294]
# Use Case

With the advent of IIIF 3.0 Specs and the future inclusion of A/V to the mix, one of the use cases we have for our repository system is to be able to use the same access/ID resolving logic we already have in place (in place == wonderful Cantaloupe) to serve Audio and Video Binaries.

I'm totally aware that its out of scope of this project to deal with media that are not image based, so basically what i would like to ask for/see is a passthrough processor. Basically something that allows me to ask for a certain identifier and if the requested format (extension) already exists in storage and the request is for FULL/no modification and/or out of scope of the supported media types (or a given set of conditions) it allows me to just get the binary directly with no processing at all.

Totally aware my request is wishful and there is a lot more in place to make this happen, but if possible (or some hint on where to look and what people would feel is adequate or even if it could be something other people could use) would love to get this option. Main reason is Cantaloupe has given us also a extremely safe way to deal with multiple backend storage mechanism and coding for that had brought us many smiles and peace of mind becoming fast a corner stone in our stack (thanks)

Lastly: is there any way i/we can contribute to this project to help with future sustainability? 

Thanks so much

**Comment by adolski** [comment]
Hi @DiegoPino,

Thanks for reporting this use case. I'm glad you are enjoying your use of Cantaloupe. :smile:

I don't think adding binary serving would be difficult, but it does make me worry about scope creep. I think it's important to keep the image server separate from other components due to the kind of work it does (which is CPU- and I/O-intensive), so that they can be scaled independently and won't bog each other down.

Also, it's a pretty big application already and I don't want to let it get out of hand, relative to the amount of time I have for it currently.

As far as contributions... a lot of the low-hanging fruit has already been picked and there are a lot of items left on my private to-do list that are time-consuming and/or difficult that I figure no one else would be interested in doing. But I do appreciate bug reports, idea reports, optimizations, or whatever.

**Comment by DiegoPino** [comment]
Hi @adolski,

Yes, i was also worried about the scope creep. Makes sense. I Can deal with the use case by writing a IIIF aware small proxy (Looking at Go right now).

Will try to be be useful here to help keep your great project moving. Thanks a lot
