### ISSUE TITLE
Log spam: Failed to initialize TurboJpegProcessor

### ISSUE THREAD

**Issue by mmatela** [cantaloupe-project/cantaloupe#304]
Follow-up on issue #287
Now Cantaloupe doesn't fail with default configuration, but a warning shows up in logs on every request:

    WARN  e.i.l.c.p.ProcessorFactory - Failed to initialize TurboJpegProcessor (error: Can't load library: /opt/libjpeg-turbo/lib/libturbojpeg.so)

Is this intentional? IMO one warning only on the first attempt would be enough. Now I have to set `ManualSelectionStrategy` again to avoid this spamming.

As a side note, I'm surprised the processors are initialized on each request. Wouldn't it be faster to reuse an already initialized instance, at least per thread? I guess the benefit now is that if I install turbojpeg, Cantalupe would catch it without restart. But it's a very minor thing.

**Comment by adolski** [comment]
Hi @mmatela, thanks for reporting. The above commit reduces the log level for this message to `debug`.

The message is a little bit misleading because "initialization" (which in this case means making sure all required dependencies are in place so that the processor will work) actually does happen only once, but the error is cached.
