### ISSUE TITLE
JRuby warning about "Illegal reflective access by com.headius.backport9.modules.Modules"

### ISSUE THREAD

**Issue by RussellMcOrmond** [cantaloupe-project/cantaloupe#393]
JRuby version 9.2.11.1 is version currently used by Cantaloupe.  While running on  OpenJDK 64-Bit Server VM 11.0.7  I get the following warning on startup:

```
18:05:02.056 [main] INFO  e.i.l.c.ApplicationContextListener - 🍈 Starting Cantaloupe 4.1.6
18:05:02.074 [main] INFO  e.i.l.c.s.HeapInvocationCache - Invocation cache limit: 15712256
18:05:02.372 [main] INFO  e.i.l.c.s.DelegateProxy - Loading script code
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.headius.backport9.modules.Modules (file:/tmp/jetty-0_0_0_0-8182-cantaloupe-4_1_6_war-_-any-14581270792193783147.dir/webapp/WEB-INF/lib/backport9-1.3.jar) to method sun.nio.ch.NativeThread.signal(long)
WARNING: Please consider reporting this to the maintainers of com.headius.backport9.modules.Modules
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

Searching I see notes suggesting that  9.2.12.0 fixes this issue, and 9.2.13.0 also exists.

**Comment by adolski** [comment]
This warning is harmless for now but could be a problem when the JRuby that is producing it is run in a future JVM that has removed support for the reflective accesss that it's warning about. JRuby has been updated on the 5.0 branch to a version that eliminates the warning, but I'm probably going to leave it be on the 4.1 branch, because I expect that 4.1 will be long out of date by the time it becomes a problem.
