### ISSUE TITLE
Understanding the FileSystemCache location for my derivatives

### ISSUE THREAD

**Issue by joelakes** [cantaloupe-project/cantaloupe#399]
Hi. I'm using Cantaloupe as the image server for a Hyrax Samvera/Fedora Commons repository. I am trying to understand how Cantaloupe calculates the file system cache location. 
e.g. I ingested a file called campus3.jpg.
MD5 of the file is: 7ba68569bb456e160260e7d2a31b6e76
MD5 of the file-name is: 1b262a61849900b102c0e598da6cf662
But Cantaloupe put the cached images here:
/var/cache/cantaloupe/image/76/3b/be so whatever it is doing it seems to arrive at the hash 763bbeeff54db9416818799da49797d2

Can you tell me how it calculates the hash?
Thanks!

**Comment by adolski** [comment]
Hi @joelakes,

The structure of FilesystemCache content is documented here: https://cantaloupe-project.github.io/manual/4.1/caching.html#FilesystemCache

I suspect what is throwing you off is that you have an image named `campus3.jpg` but are referring to it using a different identifier? Because the hash is based on the identifier, not the filename.

When I access an image with an identifier of `campus3.jpg`, the resulting cached content looks like:

```
{FilesystemCache.pathname}/info/1b/26/2a/1b262a61849900b102c0e598da6cf662.json
{FilesystemCache.pathname}/image/1b/26/2a/1b262a61849900b102c0e598da6cf662_2dd6b990b4b6bee6e5a724a703db9bb9.jpg
```

(Note that the filename of the .jpg contains two hashes, one for the identifier and one for the operation list.)

**Comment by joelakes** [comment]
Thanks @adolski, much appreciated.

When you say that the filename of the .jpg contains two hashes, what does operation list mean?

**Comment by adolski** [comment]
The arguments in an image URI (e.g. `/campus3.jpg/0,0,500,500/200,/15/default.jpg` are converted internally into an instance of `e.i.l.c.operation.OperationList`. The second hash is the hash of a serialization of that object. If you were to then request a different version of that image, the first hash would be the same but the second one different.

**Comment by joelakes** [comment]
Thanks @adolski
