### ISSUE TITLE
Add option to return an image at `max_scale` instead of throwing an error

### ISSUE THREAD

**Issue by IllyaMoskvin** [cantaloupe-project/cantaloupe#408]
Cantaloupe 4.1.6 defaults to returning `403 Forbidden` if the client requests an image that requires upscaling beyond `max_scale`:

https://github.com/cantaloupe-project/cantaloupe/commit/1eb8459cd98c7d7c86bdf5942930645d3f3588cf

Previously, this was implemented via the `allow_upscaling` option, but this has been superseded by `max_scale`:

https://github.com/cantaloupe-project/cantaloupe/commit/ff26367416bb5554f71734b9d2bb12bdc46de81a

This tripped us up during the upgrade, since the default behavior has changed to return an error, rather than allow upscaling. This new default makes sense for new installations of Cantaloupe, and I think it's good from a stability perspective.

However, it might be nice to have a configuration property that allows admins to control Cantaloupe's behavior when it receives a request for an upscaled image. The options for this property could be as follows:

1. Return `403 Forbidden` (default, current behavior)
2. Return the requested area at `max_scale`
3. Return `301 Redirect` to URI that's scale-constrained
4. Return `302 Redirect` to URI that's scale-constrained

I'm not sure about the feasibility of this suggestion – maybe this is an XY problem? – but I thought I'd document it here while we are working to resolve the issue on our end.

**Comment by adolski** [comment]
Hi @IllyaMoskvin,

I'm not sure what the problem is here. Are you trying to maintain the behavior of pre-4.1 versions? If so, setting `max_scale = 0` should achieve the same result as `allow_upscaling = true`.

I do see that removal of `allow_upscaling` is missing from the [upgrade guide](https://github.com/cantaloupe-project/cantaloupe/blob/release/4.1/UPGRADING.md), so I will make a note to add it and explain that it is replaced by `max_scale`.

**Comment by IllyaMoskvin** [comment]
Hi @adolski, this is a feature suggestion.

The problem that we are trying to solve is that there are existing applications which depend on our IIIF server, and these applications were programmed to not respect scale limitations. Yes, we solved that problem by setting `max_scale = 0`.

But I recognize that there is a purpose to the `max_scale` option, too: it mitigates the server from being burdened by upscaling requests. So by setting `max_scale = 0`, we fixed the problem of images breaking in legacy applications, but we "reintroduced" the problem of overburdening that `max_scale` was trying to solve.

I'm suggesting that there might be a way to take advantage of `max_scale`, while not outright returning `403 Forbidden`. If the server returns an image of a different size than expected (or a redirect to one), the client is less likely to break than if the server returns an error outright. It might be nice to have the option to enable such behavior.

**Comment by adolski** [comment]
Thanks @IllyaMoskvin, I get it now.

[Section 5.3](https://iiif.io/api/image/2.1/#profile-description) of the Image API 2.1 specification says:

> If maxWidth alone, or maxWidth and maxHeight are specified then clients should expect requests with larger linear dimensions to be rejected. If maxArea is specified then clients should expect requests with larger pixel areas to be rejected. The maxWidth / maxHeight and maxArea parameters are independent, servers may implement either or both limits. ... Clients should not make requests that exceed size limits expressed.

This makes a client's responsibility pretty clear: it should check the info.json first and expect out-of-bounds requests to be rejected. It doesn't define "rejected," but certainly HTTP 403 is a clear rejection. The rejection is important for clients because it forces them to back up and check their behavior. A redirect (for example) doesn't help them do this--it just refers them to some other resource that they might not even want, for reasons that they might not understand. (Same story with regard to fulfilling the request with a smaller image, but this would also break caches.)

So, it seems that this feature is basically a toggle switch between "adhere to the spec" and "adhere loosely (or maybe not quite) to the spec." I don't want to implement something like that for obvious reasons. I think that correcting your clients' behavior is the correct way to proceed here.

**Comment by IllyaMoskvin** [comment]
Thanks for the explanation, @adolski. That makes sense. Although it can be a hassle to correct the behavior of legacy or external clients, it's probably better to be strict than forgiving in the long run. I'm closing the issue.
