### ISSUE TITLE
CORS Policy

### ISSUE THREAD

**Issue by erikradisch** [cantaloupe-project/cantaloupe#416]
Is there any possibility to deactivate the Access-Controll-Allow-Origin : * response header? I cannot pass ajax headers for access controll if this flag is set...

By the way, this is an issue with 4.1.7.

**Comment by adolski** [comment]
That header is advised in the Image API specification: https://iiif.io/api/image/2.1/#image-information-request

There is no way to disable it -- the only option would be to remove or change it using a reverse proxy.

**Comment by erikradisch** [comment]
thanks, the tipp with the proxy helped.

**Comment by ewg118** [comment]
I want to follow up on this because I am migrating from Loris to Cantaloupe, which means the URL pattern for IIIF images is different. I am configuring Apache to forward server.org/(.*) to server.org/iiif/2/$1. The forwarding part works, but the issue is that the client browser is generating a CORS-related error.

If I remove `Header always set Access-Control-Allow-Origin "*"` from my Apache config, I will get a client error that CORS has not been set in the header of the original URL pattern, so the client will not display the IIIF tiles. If I add `Header always set Access-Control-Allow-Origin "*"` back into my Apache config, I get a different error that the new Cantaloupe URL pattern is blocked because two CORS headers are disallowed by the client. I need to figure out how to suppress the header from Cantaloupe so that I can override it with the Apache config.

I can't rename a million file URLs in the database.

**Comment by DiegoPino** [comment]
@ewg118. The solution is still the same. Proxying. Not redirecting (forwarding). 

The docs have more info (examples are for base domain... so you want to have a location or location match instead if you are serving many things under the same domain/different paths)
https://cantaloupe-project.github.io/manual/3.4/deployment.html#Reverse-ProxyingApache
If you REALLY need to set the header manually, it should go in your apache virtual-host inside a `location` or `locationMatch`.

But in theory you should not need that at all when proxying, bc the idea (of proxying) is that you forward whatever header you need from your Front to the back (as the docs show) so Cantaloupe does not act on its own localhost:8183 reality/path (or wherever you have it) but on the front end info sent via headers.

An example of overriding this manually ... via apache (not a fully working solution) would look like this.

```
 <LocationMatch "/youroldstuff/">
    ProxyPass http://localhost:8183/iiif/2
    ProxyPassReverse http://localhost:8183/iiif/2
    Header add Access-Control-Allow-Origin "*"
  </LocationMatch>
```

**Comment by ewg118** [comment]
I couldn't find documentation on how to apply a header to a forward. The ProxyPass is also less than ideal, and I had to refer to the old thread https://github.com/cantaloupe-project/cantaloupe/issues/595#issuecomment-1910508364 in order to override the `@id` URI in the info.json. My preference is for URL patterns to be more application agnostic so that you can migrate from one IIIF server to another without jumping through a lot of hoops in order to preserve functionality of URIs that have propagated all over the web.

**Comment by DiegoPino** [comment]
If you can't forward headers from Frontend to backend (bc of the redirect) you can set `base_uri` , as in the docs
> If the proxy cannot be configured to send the X-Forwarded headers, the base_uri configuration option can be used instead; set it to the URI of the client-facing reverse proxy including any base path.
to rewrite your info.json responses.

But you can also do some header mangling, e.g *(unset/set new ones)
See:
https://httpd.apache.org/docs/2.4/en/mod/mod_headers.html#header

and this
https://stackoverflow.com/questions/690521/how-to-add-additional-headers-to-302-redirects-in-apache
