### ISSUE TITLE
gamma correction (or: resize in linear photon space)

### ISSUE THREAD

**Issue by jbarth-ubhd** [cantaloupe-project/cantaloupe#441]
Dear reader, this image:

https://digi.ub.uni-heidelberg.de/iiif/2/testjbx%3Ax.jpg/full/500,/0/default.jpg

is of size 500×500 px in original and should look like an gray square - even if scaled down.

But if scaled down, a dark filled circle shows up:

https://digi.ub.uni-heidelberg.de/iiif/2/testjbx%3Ax.jpg/full/400,/0/default.jpg

Is there an option to do conversion to linear photon space before scaling and back to srgb afterwards?

We have lots of woodcut images where scaling should be done in the best possible way.

**Comment by adolski** [comment]
This is a good idea and I will put it on the to-do list for 5.0.

**Comment by adolski** [comment]
On `develop` there is a new `processor.downscale_linear` config key that enables downscaling in linear RGB space. There are a couple of caveats:

1. It will cause a performance hit due to the extra conversion into and out of linear space.
2. It only works with mono-resolution images--not pyramidal. (I guess you could manually generate pyramidal TIFFs whose pyramid levels have been downscaled this way... but not an option for JP2.)

I believe this resolves the issue--if not, let me know.
