### ISSUE TITLE
WebP Support | Cantaloupe 5.x

### ISSUE THREAD

**Issue by sraeuchle** [cantaloupe-project/cantaloupe#470]
Hi there, 

first of all, congratulations for that great Software!

In the current version 5.0 you removed the ImageMagicProcessor which also means there is no WebP support any more.
Is there a way to setup a Cantaloupe 5.0 including WebP support?

**Comment by adolski** [comment]
Hi @sraeuchle,

Unfortunately, WebP won't be available in the 5.0 series. ImageMagickProcessor had to be removed as a first step in a redesign process (explained in #388) that aims to make it possible to provide format support using Java Image I/O plugins.

I will be looking into adding back WebP support in the next major version. Because there is no open-source Java WebP codec, it will probbaly have to involve calling into libwebp, which is not necessarily easy from Java, but we'll see.

**Comment by sraeuchle** [comment]
@adolski 

Thanks for the fast response.

I will look forward for the next major versions.
